backend/n1mapp/config/routes.rb
Rails.application.routes.draw do
  resources :sexual_aggressions
  resources :other_aggressions
  resources :aggression_details
  #the next line after the comma instructs devise for use a different controller than the one in the devise gem
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}
  #resources :users
  resources :categories
  resources :help_centers

  namespace 'api' do
    namespace 'v1' do
      post 'auth_user' => 'authentication#authenticate_user'
      resources :help_centers
      resources :users
    end
  end



  get 'admin_pages/dashboard'
  get 'admin_pages/users_query'
  get 'static_pages/landing'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#landing'
  
  #root 'users#sign_in'
end

backend/n1mapp/app/models/aggression_detail.rb
class AggressionDetail < ApplicationRecord
  belongs_to :user
  has_many :sexual_aggressions, dependent: :destroy
  has_many :other_aggressions, dependent: :destroy
end

backend/n1mapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/n1mapp/app/models/category.rb
class Category < ApplicationRecord
  belongs_to :help_centers
end

backend/n1mapp/app/models/help_center.rb
class HelpCenter < ApplicationRecord
    has_many :categories ,dependent: :destroy
end

backend/n1mapp/app/models/other_aggression.rb
class OtherAggression < ApplicationRecord
  belongs_to :aggression_detail
end

backend/n1mapp/app/models/sexual_aggression.rb
class SexualAggression < ApplicationRecord
  belongs_to :aggression_detail
end

backend/n1mapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :aggression_details, dependent: :destroy
  
  

  #this is the 1st query
  def self.get_details
    self.joins(:aggression_details).select("name,surname,district,aggression_date,aggression_time,scene,mechanism,aggression_details.id", "admin_user")
  end
  #this is the 2nd query
  def self.get_users
    select("name","surname","email", "phone_number","document_type", "document_number", "district", "admin_user", "attendant_name", "attendant_phone_number", "sexual_orientation" ).where(admin_user: false)
  end
  
  #this callback is to set default values by calling the "init" function below
  after_initialize :init
 
  #only default booleans to 'false' if they're 'nil' to avoid overwriting a 'true'
  def init 
    self.admin_user = false if self.admin_user.nil?
  end


end

backend/n1mapp/app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  def dashboard
    @details = User.get_details
  end

  def users_query
    @users = User.get_users
  end

end

backend/n1mapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_params, if: :devise_controller?
def hello
    render html: "Bienvenido a NiUnaMas"
    
end

def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
end
end

backend/n1mapp/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:help_centers_id, :institution_category)
    end
end

backend/n1mapp/app/controllers/help_centers_controller.rb
class HelpCentersController < ApplicationController
  before_action :set_help_center, only: [:show, :edit, :update, :destroy]

  # GET /help_centers
  # GET /help_centers.json
  def index
    @help_centers = HelpCenter.all
  end

  # GET /help_centers/1
  # GET /help_centers/1.json
  def show
  end

  # GET /help_centers/new
  def new
    @help_center = HelpCenter.new
  end

  # GET /help_centers/1/edit
  def edit
  end

  # POST /help_centers
  # POST /help_centers.json
  def create
    @help_center = HelpCenter.new(help_center_params)

    respond_to do |format|
      if @help_center.save
        format.html { redirect_to @help_center, notice: 'Help center was successfully created.' }
        format.json { render :show, status: :created, location: @help_center }
      else
        format.html { render :new }
        format.json { render json: @help_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /help_centers/1
  # PATCH/PUT /help_centers/1.json
  def update
    respond_to do |format|
      if @help_center.update(help_center_params)
        format.html { redirect_to @help_center, notice: 'Help center was successfully updated.' }
        format.json { render :show, status: :ok, location: @help_center }
      else
        format.html { render :edit }
        format.json { render json: @help_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /help_centers/1
  # DELETE /help_centers/1.json
  def destroy
    @help_center.destroy
    respond_to do |format|
      format.html { redirect_to help_centers_url, notice: 'Help center was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help_center
      @help_center = HelpCenter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def help_center_params
      params.require(:help_center).permit(:name, :latitude, :longitude, :phone_number, :picture, :schedule, :address)
    end
end

backend/n1mapp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end
end

backend/n1mapp/app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

backend/n1mapp/app/helpers/aggression_details_helper.rb
module AggressionDetailsHelper
end

backend/n1mapp/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/n1mapp/app/helpers/categories_helper.rb
module CategoriesHelper
end

backend/n1mapp/app/helpers/help_centers_helper.rb
module HelpCentersHelper
end

backend/n1mapp/app/helpers/other_aggressions_helper.rb
module OtherAggressionsHelper
end

backend/n1mapp/app/helpers/sexual_aggressions_helper.rb
module SexualAggressionsHelper
end

backend/n1mapp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

backend/n1mapp/app/views/layouts/password.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <!--
  <link rel="stylesheet" href="../../bower_components/bootstrap/dist/css/bootstrap.min.css">
  -->


  <!-- Font Awesome -->
  <!--
  <link rel="stylesheet" href="../../bower_components/font-awesome/css/font-awesome.min.css">
  -->

  <!-- Ionicons -->
  <!--
  <link rel="stylesheet" href="../../bower_components/Ionicons/css/ionicons.min.css">
  -->

  <!-- Theme style -->
  <!--
  <link rel="stylesheet" href="../../dist/css/AdminLTE.min.css">
  -->
  
  <!-- iCheck -->
  <link rel="stylesheet" href="../../plugins/iCheck/square/blue.css">
  

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="sign_in"><b>Olvidaste</b>Password?</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Recupera tu password</p>

    

    <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
    <%= devise_error_messages! %>
      <div class="field">

      <!--This is the email field-->
      <div class="form-group has-feedback">
        <%= f.label :email %><br />
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "Email"  %>
        
      </div>
      <!--This is the password field-->
      <div class="form-group has-feedback">
        <%= f.label :password %><br />
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        <%= f.password_field :password, autocomplete: "current-password", class: "form-control", placeholder: "Password" %>
      </div>

        <div class="row">
        <div class="col-xs-8">
          <a href="/users/sign_in.html" class="text-center">Iniciar sesión</a><br>
          <a href="/users/sign_up.html" class="text-center">Crear una cuenta</a>
        </div>
        <!-- /.col -->
        <div class="col-xs-12">
          
          <%= f.submit "Enviar instrucciones para reiniciar password", class: "btn btn-primary btn-block btn-flat" %>
        </div>
        <!-- /.col -->
      </div>
    <% end %>
   

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="../../bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../../plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>

</body>
</html>

backend/n1mapp/app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <!--
  <link rel="stylesheet" href="../../bower_components/bootstrap/dist/css/bootstrap.min.css">
  -->


  <!-- Font Awesome -->
  <!--
  <link rel="stylesheet" href="../../bower_components/font-awesome/css/font-awesome.min.css">
  -->

  <!-- Ionicons -->
  <!--
  <link rel="stylesheet" href="../../bower_components/Ionicons/css/ionicons.min.css">
  -->

  <!-- Theme style -->
  <!--
  <link rel="stylesheet" href="../../dist/css/AdminLTE.min.css">
  -->
  
  <!-- iCheck -->
  <link rel="stylesheet" href="../../plugins/iCheck/square/blue.css">
  

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="sign_in"><b>Admin</b>NiUna+</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Inicie su sesión</p>

    

    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">

      <!--This is the email field-->
      <div class="form-group has-feedback">
        <%= f.label :email %><br />
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "Email"  %>
        
      </div>
      <!--This is the password field-->
      <div class="form-group has-feedback">
        <%= f.label :password %><br />
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        <%= f.password_field :password, autocomplete: "current-password", class: "form-control", placeholder: "Password" %>
      </div>

    <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :recordarme %>
    </div>
    <% end -%>




      <div class="row">
        <div class="col-xs-8">
          <a href="password/new">Olvide mi password</a><br>
          <a href="sign_up.html" class="text-center">Crear una cuenta</a>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit "Ingresar", class: "btn btn-primary btn-block btn-flat" %>
        </div>
        <!-- /.col -->
      </div>
    <% end %>
   

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="../../bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../../plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>

</body>
</html>

backend/n1mapp/app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  
  <!-- Bootstrap 3.3.7 -->
  <!---- this link is replace by @import in applicactions.scss
  <link rel="stylesheet" href="../../bower_components/bootstrap/dist/css/bootstrap.min.css">
  -->

  
  <!-- Font Awesome -->
  <!---- this link is replace by @import in applicactions.scss
  <link rel="stylesheet" href="../../bower_components/font-awesome/css/font-awesome.min.css">
  -->

  <!-- Ionicons -->
  <!-- this link is replace by @import in applicactions.scss
  <link rel="stylesheet" href="../../bower_components/Ionicons/css/ionicons.min.css">
  -->

  <!-- Theme style -->
  <!-- this link is replace by @import in applicactions.scss
  <link rel="stylesheet" href="../../dist/css/AdminLTE.min.css">
  -->

  <!-- iCheck -->
  <link rel="stylesheet" href="../../plugins/iCheck/square/blue.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="sign_up.html"><b>Admin</b>NiUna+</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">Registro nuevo funcionario</p>
    
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>

      <div class="form-group has-feedback">
      <%= f.label :Nombre %><br />
      <span class="glyphicon glyphicon-user form-control-feedback"></span>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"Nombre" %>
      </div>

      <div class="form-group has-feedback">
      <%= f.label :email %><br />
      <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder:"Email" %>
      </div>

      <div class="form-group has-feedback">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      <%= f.password_field :password, autocomplete: "new-password", class:"form-control", placeholder:"Password" %>
      </div>

      <div class="form-group has-feedback">
      <%= f.label :password_confirmar %><br />
      <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control", placeholder:"Confirmar Password" %>
      </div>
      
      <div class="row">
        <div class="col-xs-8">
          <a href="sign_in.html" class="text-center">Ya estoy registrado</a>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit "Registrarse", class:"btn btn-primary btn-block btn-flat" %>
        </div>
        <!-- /.col -->
      </div>
  
    <% end %>
  

  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->

<!-- jQuery 3 -->
<script src="../../bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../../plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>

</body>
</html>