backend/n1mapp/config/routes.rb
Rails.application.routes.draw do
  resources :sexual_aggressions
  resources :other_aggressions
  resources :aggression_details
  #the next line after the comma instructs devise for use a different controller than the one in the devise gem
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}
  #resources :users
  resources :categories
  resources :help_centers

  namespace 'api' do
    namespace 'v1' do
      post 'auth_user' => 'authentication#authenticate_user'
      resources :help_centers
      resources :users
    end
  end



  get 'admin_pages/dashboard'
  get 'admin_pages/users_query'
  get 'static_pages/landing'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#landing'
  
  #root 'users#sign_in'
end

backend/n1mapp/app/models/other_aggression.rb
class OtherAggression < ApplicationRecord
  belongs_to :aggression_detail
end

backend/n1mapp/app/controllers/other_aggressions_controller.rb
class OtherAggressionsController < ApplicationController
  before_action :set_other_aggression, only: [:show, :edit, :update, :destroy]

  # GET /other_aggressions
  # GET /other_aggressions.json
  def index
    @other_aggressions = OtherAggression.all
  end

  # GET /other_aggressions/1
  # GET /other_aggressions/1.json
  def show
  end

  # GET /other_aggressions/new
  def new
    @other_aggression = OtherAggression.new
  end

  # GET /other_aggressions/1/edit
  def edit
  end

  # POST /other_aggressions
  # POST /other_aggressions.json
  def create
    @other_aggression = OtherAggression.new(other_aggression_params)

    respond_to do |format|
      if @other_aggression.save
        format.html { redirect_to @other_aggression, notice: 'Other aggression was successfully created.' }
        format.json { render :show, status: :created, location: @other_aggression }
      else
        format.html { render :new }
        format.json { render json: @other_aggression.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /other_aggressions/1
  # PATCH/PUT /other_aggressions/1.json
  def update
    respond_to do |format|
      if @other_aggression.update(other_aggression_params)
        format.html { redirect_to @other_aggression, notice: 'Other aggression was successfully updated.' }
        format.json { render :show, status: :ok, location: @other_aggression }
      else
        format.html { render :edit }
        format.json { render json: @other_aggression.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /other_aggressions/1
  # DELETE /other_aggressions/1.json
  def destroy
    @other_aggression.destroy
    respond_to do |format|
      format.html { redirect_to other_aggressions_url, notice: 'Other aggression was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_other_aggression
      @other_aggression = OtherAggression.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def other_aggression_params
      params.require(:other_aggression).permit(:aggression_detail_id, :name, :description)
    end
end

backend/n1mapp/app/helpers/other_aggressions_helper.rb
module OtherAggressionsHelper
end

backend/n1mapp/app/views/other_aggressions/_form.html.erb
<%= form_with(model: other_aggression, local: true) do |form| %>
  <% if other_aggression.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(other_aggression.errors.count, "error") %> prohibited this other_aggression from being saved:</h2>

      <ul>
      <% other_aggression.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :aggression_detail_id %>
    <%= form.text_field :aggression_detail_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/n1mapp/app/views/other_aggressions/edit.html.erb
<h1>Editing Other Aggression</h1>

<%= render 'form', other_aggression: @other_aggression %>

<%= link_to 'Show', @other_aggression %> |
<%= link_to 'Back', other_aggressions_path %>

backend/n1mapp/app/views/other_aggressions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Other Aggressions</h1>

<table>
  <thead>
    <tr>
      <th>Aggression detail</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @other_aggressions.each do |other_aggression| %>
      <tr>
        <td><%= other_aggression.aggression_detail %></td>
        <td><%= other_aggression.name %></td>
        <td><%= other_aggression.description %></td>
        <td><%= link_to 'Show', other_aggression %></td>
        <td><%= link_to 'Edit', edit_other_aggression_path(other_aggression) %></td>
        <td><%= link_to 'Destroy', other_aggression, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Other Aggression', new_other_aggression_path %>

backend/n1mapp/app/views/other_aggressions/new.html.erb
<h1>New Other Aggression</h1>

<%= render 'form', other_aggression: @other_aggression %>

<%= link_to 'Back', other_aggressions_path %>

backend/n1mapp/app/views/other_aggressions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aggression detail:</strong>
  <%= @other_aggression.aggression_detail %>
</p>

<p>
  <strong>Name:</strong>
  <%= @other_aggression.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @other_aggression.description %>
</p>

<%= link_to 'Edit', edit_other_aggression_path(@other_aggression) %> |
<%= link_to 'Back', other_aggressions_path %>