backend/n1mapp/config/routes.rb
Rails.application.routes.draw do
  resources :sexual_aggressions
  resources :other_aggressions
  resources :aggression_details
  #the next line after the comma instructs devise for use a different controller than the one in the devise gem
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}
  #resources :users
  resources :categories
  resources :help_centers

  namespace 'api' do
    namespace 'v1' do
      post 'auth_user' => 'authentication#authenticate_user'
      resources :help_centers
      resources :users
    end
  end



  get 'admin_pages/dashboard'
  get 'admin_pages/users_query'
  get 'static_pages/landing'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#landing'
  
  #root 'users#sign_in'
end

backend/n1mapp/app/models/help_center.rb
class HelpCenter < ApplicationRecord
    has_many :categories ,dependent: :destroy
end

backend/n1mapp/app/controllers/api/v1/help_centers_controller.rb
module Api
    module V1
        class HelpCentersController < ApiApplicationController
            before_action :authenticate_request!
            def index
                hcenters = HelpCenter.order('name DESC');
                render json: {status: 'SUCCESS', message: 'Carga de sitios de ayuda', data: hcenters}, status: :ok
            end

            def show
                hcenter = HelpCenter.find(params[:id])
                render json: {status: 'SUCCESS', message: 'Carga sitio de ayuda', data: hcenter}, status: :ok
            end

        end
    end
end

backend/n1mapp/app/controllers/help_centers_controller.rb
class HelpCentersController < ApplicationController
  before_action :set_help_center, only: [:show, :edit, :update, :destroy]

  # GET /help_centers
  # GET /help_centers.json
  def index
    @help_centers = HelpCenter.all
  end

  # GET /help_centers/1
  # GET /help_centers/1.json
  def show
  end

  # GET /help_centers/new
  def new
    @help_center = HelpCenter.new
  end

  # GET /help_centers/1/edit
  def edit
  end

  # POST /help_centers
  # POST /help_centers.json
  def create
    @help_center = HelpCenter.new(help_center_params)

    respond_to do |format|
      if @help_center.save
        format.html { redirect_to @help_center, notice: 'Help center was successfully created.' }
        format.json { render :show, status: :created, location: @help_center }
      else
        format.html { render :new }
        format.json { render json: @help_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /help_centers/1
  # PATCH/PUT /help_centers/1.json
  def update
    respond_to do |format|
      if @help_center.update(help_center_params)
        format.html { redirect_to @help_center, notice: 'Help center was successfully updated.' }
        format.json { render :show, status: :ok, location: @help_center }
      else
        format.html { render :edit }
        format.json { render json: @help_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /help_centers/1
  # DELETE /help_centers/1.json
  def destroy
    @help_center.destroy
    respond_to do |format|
      format.html { redirect_to help_centers_url, notice: 'Help center was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help_center
      @help_center = HelpCenter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def help_center_params
      params.require(:help_center).permit(:name, :latitude, :longitude, :phone_number, :picture, :schedule, :address)
    end
end

backend/n1mapp/app/helpers/help_centers_helper.rb
module HelpCentersHelper
end

backend/n1mapp/app/views/help_centers/_form.html.erb
<%= form_with(model: help_center, local: true) do |form| %>
  <% if help_center.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(help_center.errors.count, "error") %> prohibited this help_center from being saved:</h2>

      <ul>
      <% help_center.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="field">
    <%= form.label :schedule %>
    <%= form.text_field :schedule %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/n1mapp/app/views/help_centers/edit.html.erb
<h1>Editing Help Center</h1>

<%= render 'form', help_center: @help_center %>

<%= link_to 'Show', @help_center %> |
<%= link_to 'Back', help_centers_path %>

backend/n1mapp/app/views/help_centers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de centros de ayuda publicados en al app mobil</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Phone number</th>
      <th>Picture</th>
      <th>Schedule</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @help_centers.each do |help_center| %>
      <tr>
        <td><%= help_center.name %></td>
        <td><%= help_center.latitude %></td>
        <td><%= help_center.longitude %></td>
        <td><%= help_center.phone_number %></td>
        <td><%= help_center.picture %></td>
        <td><%= help_center.schedule %></td>
        <td><%= help_center.address %></td>
        <td><%= link_to 'Show', help_center %></td>
        <td><%= link_to 'Edit', edit_help_center_path(help_center) %></td>
        <td><%= link_to 'Destroy', help_center, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Help Center', new_help_center_path %>

backend/n1mapp/app/views/help_centers/new.html.erb
<h1>Creación de nuevo centro de ayuda</h1>

<%= render 'form', help_center: @help_center %>

<%= link_to 'Back', help_centers_path %>

backend/n1mapp/app/views/help_centers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @help_center.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @help_center.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @help_center.longitude %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @help_center.phone_number %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @help_center.picture %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @help_center.schedule %>
</p>

<p>
  <strong>Address:</strong>
  <%= @help_center.address %>
</p>

<%= link_to 'Edit', edit_help_center_path(@help_center) %> |
<%= link_to 'Back', help_centers_path %>